kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: am-vol
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem