apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: grafana-helm
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2021-05-31T07:48:54Z"
  labels:
    app.kubernetes.io/instance: grafana-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.5
    helm.sh/chart: grafana-6.9.1
  name: grafana-helm
  namespace: monitoring
  resourceVersion: "408901189"
  uid: 65ee7ecd-c928-4384-b0cf-0fcf8d9c82b0
