{
 "title": "Kubernetes App Metrics",
 "description": "After selecting your namespace and container you get a wealth of metrics like request rate, error rate, response times, pod count, cpu and memory usage. You can view cpu and memory usage in a variety of ways, compared to the limit, compared to the request, per pod, average per pod, etc.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container_name!=\"POD\"},namespace)"
   },
   {
    "name": "container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container_name!=\"POD\"},container_name)"
   }
  ]
 },
 "panels": [
  { "title": "Request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app,code)",
     "legendFormat": "native | {{code}}"
    },
    {
     "expr": "sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app,status)",
     "legendFormat": "nginx | {{status}}"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,code)",
     "legendFormat": "haproxy | {{code}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\",code=\"5xx\"}[30s])) by (app,kubernetes_namespace) / sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace)",
     "legendFormat": "haproxy"
    },
    {
     "expr": "sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\", code=~\"5[0-9]+\"}[30s])) by (kubernetes_namespace,app) / sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app)",
     "legendFormat": "native"
    },
    {
     "expr": "sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\", status=~\"5[0-9]+\"}[30s])) by (kubernetes_namespace,app) / sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app)",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time percentiles",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.50"
      }
     ]
    }
   ]
  },
  { "title": "Pod count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (pod_name))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (kubernetes_io_hostname))",
     "legendFormat": "hosts"
    }
   ]
  },
  { "title": "Usage relative to request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cpu usage (relative to request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container_name) / sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name)",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container_name) / sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name)",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Usage relative to limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (relative to limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container_name) / sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
       "legendFormat": "actual"
      }
     ]
    },
    {
     "title": "Memory usage (relative to limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
       "legendFormat": "actual"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage per pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (per pod)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (id,pod_name)",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "limit"
      },
      {
       "expr": "sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) / count(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "Memory usage (per pod)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (id,pod_name)",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (container_name,namespace)",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  { "title": "Usage per pod (average)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Cpu usage (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) / count(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Usage total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Cpu usage (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container_name)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes cluster monitoring (via Prometheus)",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (systemd_service_name)",
       "legendFormat": "{{systemd_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{pod_name}} | {{container_name}}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{kubernetes_io_hostname}} | {{rkt_container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (systemd_service_name)",
       "legendFormat": "{{systemd_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{pod_name}} | {{container_name}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{kubernetes_io_hostname}} | {{rkt_container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{pod_name}}"
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{pod_name}} | {{container_name}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{pod_name}} | {{container_name}}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "-> docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "<- docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "-> rkt: {{kubernetes_io_hostname}} | {{rkt_container_name}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "<- rkt: {{kubernetes_io_hostname}} | {{rkt_container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "-> {{id}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "<- {{id}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "MongoDB",
 "description": "MongoDB Prometheus Exporter Dashboard. \r\nWorks well with https://github.com/dcu/mongodb_exporter\r\n\r\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(mongodb_connections, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_query_executor_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "env" },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_replset_number_of_members{instance=~\"$env\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_replset_member_health{instance=~\"$env\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "graph",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_replset_member_state{instance=~\"$env\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Health metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$env\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$env\",state=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$env\",state=\"current\"}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Oplog Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000 or irate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000)",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Reads Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed{instance=~\"shr.*\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed{instance=~\"shr.*\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  }
 ]
}