apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIRAJnIeygcVb/YP8NIQERD5sUwDQYJKoZIhvcNAQELBQAw
    LzEtMCsGA1UEAxMkODQ4NTc5ZmQtMGRjZS00N2JlLWIwNmMtOGRkY2MzZmIwMTE0
    MB4XDTE4MTEwNTE1MzUzNloXDTIzMTEwNDE2MzUzNlowLzEtMCsGA1UEAxMkODQ4
    NTc5ZmQtMGRjZS00N2JlLWIwNmMtOGRkY2MzZmIwMTE0MIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEAjwxMW1RFPvBBIRHh45kiGyltuxC2pBYysKWzgjhi
    OCvqIgIr9qDTdK9UG83sDSev1U6LZcpFK/Qd1PPe8AyNHFKefHz63u2YxNiUr4V1
    qtnJDIlFrd4FXdsVbm1ebYcalHP4CoFF6YtYIyPvSc9rg3W0Ht6HGLZ7WCgh38Yo
    k4AzhpjWg9F0YajAZhRfVl16ye0p85FbQ/nIcpqSpL4/oEzO9ucUdMN//aeQLAYT
    AykIqrrozQkzexDsGs5q0ziKMRLSlsvaa5jzDyDQIilWYvBNO4nrONIfLmYn+8IU
    SAUltWrR4KghRnOp0ijVSYZwilL0fFYw8+oShEqabvXztQIDAQABoyMwITAOBgNV
    HQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEA
    Y7KvqecycTYfq+yvQYwKXuKba/xmaY/WMk5BM+blrV5ENmAJNJssGcxYMj+9TBvI
    d/F7wMtu0OdyCE06BZfPQQVetfUwCqUgXtDjBwdfwslSHVUNaXYfh1ajNXGV/F75
    EdskJsaJDvis+arJuO0VhKOjfSZtllmPiGIb+AnwJVj+ICGq/TSSXH9t7JyKZMJF
    r4R0bRgCXOMEJg/o13d8ZHroyPkj2BTh4UihNeyJiK8dz/48DHrSOL4b2yhKkmg9
    5bnhfxdNGR/usTYcgb1gHhjDKqX9t5LYAj791Zd3cTkGxaj6jOTX7sDuCJolWBT4
    PtfB9gJvSeLqxUjTzLJleQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-23T07:10:02Z"
  name: kube-root-ca.crt
  namespace: monitoring
  resourceVersion: "402835656"
  uid: a270ded8-de83-4325-bbe0-7c5aaeb38ec2
