{
 "title": "Kubernetes Nginx Ingress Controller",
 "description": "Dashboard for ingress-nginx",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_ingress_controller_config_hash{app=~\"$app\"}, namespace)"
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "singlestat",
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_class=~\"$controller_class\",namespace=~\"$namespace\",status!~\"[4-5].*\"}[1m])) / sum(rate(nginx_ingress_controller_requests{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{controller_class=~\"$controller_class\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active Config Failures",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nginx_ingress_controller_config_last_reload_successful{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}==0"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "[Ingress] Throughput [rpm]",
   "type": "graph",
   "description": "[rate 1m] [rpm]",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests[1m])) by (status) > 0 ",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "[Ingress] Nginx Connections",
   "type": "graph",
   "description": "Ingress Nginx'es connection types",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total[1m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "2xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"2.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "3xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"3.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "4xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"4.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "5xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"5.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "RPM Total",
   "type": "singlestat",
   "description": "All Status Code",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])) ",
     "legendFormat": "nginx"
    }
   ]
  }
 ]
}
{
 "title": "Request Handling Performance",
 "tags": [ "nginx" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "ingress",
    "label": "Service Ingress",
    "query": "label_values(nginx_ingress_controller_requests, ingress) "
   }
  ]
 },
 "panels": [
  {
   "title": "Total request handling time",
   "type": "graph",
   "description": "Total time taken for nginx and upstream servers to process a request and send a response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "graph",
   "description": "The time spent on receiving the response from the upstream server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Request volume by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "  sum by (path)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Median upstream response time by Path",
   "type": "graph",
   "description": "For each path observed, its median upstream response time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  .5,\n  sum by (le, path)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n        ingress =~ \"$ingress\"\n      }[1m]\n    )\n  )\n)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error rate by Path",
   "type": "graph",
   "description": "Percentage of 4xx and 5xx responses among all responses.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{\n  ingress = \"$ingress\",\n  status =~ \"[4-5].*\"\n}[1m])) / sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count{\n  ingress = \"$ingress\",\n}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream time consumed by Path",
   "type": "graph",
   "description": "For each path observed, the sum of upstream request time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_response_duration_seconds_sum{ingress = \"$ingress\"}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response error volume by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "  sum (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{\n        ingress =~ \"$ingress\",\n        status =~\"[4-5].*\",\n      }[1m]\n    )\n  ) by(path, status)\n",
     "legendFormat": "{{ path }} {{ status }}"
    }
   ]
  },
  {
   "title": "Average response size by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate (\n      nginx_ingress_controller_response_size_sum {\n        ingress =~ \"$ingress\",\n      }[1m]\n  )\n)  by (path) / sum (\n  rate(\n      nginx_ingress_controller_response_size_count {\n        ingress =~ \"$ingress\",\n      }[1m]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Upstream service latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(\n      nginx_ingress_controller_ingress_upstream_latency_seconds_sum {\n        ingress =~ \"$ingress\",\n      }[1m]\n)) / sum (\n  rate(\n      nginx_ingress_controller_ingress_upstream_latency_seconds_count {\n        ingress =~ \"$ingress\",\n      }[1m]\n  )\n)\n",
     "legendFormat": "average"
    }
   ]
  }
 ]
}