kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prom-vol
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
  volumeMode: Filesystem