apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"alertmanager-bot","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"alertmanager-bot"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"alertmanager-bot"},"name":"alertmanager-bot"},"spec":{"containers":[{"env":[{"name":"LISTEN_ADDR","value":"0.0.0.0:8080"},{"name":"ALERTMANAGER_URL","value":"http://alertmanager:9093/alertmanager/"},{"name":"BOLT_PATH","value":"/data/bot.db"},{"name":"STORE","value":"bolt"},{"name":"TELEGRAM_ADMIN","value":"500880383\n"},{"name":"TELEGRAM_TOKEN","value":"747792069:AAFir4hsXYX_TJCqD9llq7LlFiKesvlrXzI"}],"image":"metalmatze/alertmanager-bot:0.3.1","name":"alertmanager-bot","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"0.1","memory":"30Mi"},"requests":{"cpu":"0.01","memory":"10Mi"}},"volumeMounts":[{"mountPath":"/data","name":"alertmanager-bot"}]}],"volumes":[{"name":"alertmanager-bot","persistentVolumeClaim":{"claimName":"alertmanager-bot-vol"}}]}}}}
  creationTimestamp: "2018-11-08T16:43:24Z"
  generation: 5
  name: alertmanager-bot
  namespace: monitoring
  resourceVersion: "738596997"
  uid: 68d9100e-e375-11e8-873c-42010a800271
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertmanager-bot
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager-bot
      name: alertmanager-bot
    spec:
      containers:
      - env:
        - name: LISTEN_ADDR
          value: 0.0.0.0:8080
        - name: ALERTMANAGER_URL
          value: http://alertmanager:9093/alertmanager/
        - name: BOLT_PATH
          value: /data/bot.db
        - name: STORE
          value: bolt
        - name: TELEGRAM_ADMIN
          value: |
            500880383
        - name: TELEGRAM_TOKEN
          value: 747792069:AAFir4hsXYX_TJCqD9llq7LlFiKesvlrXzI
        image: metalmatze/alertmanager-bot:0.3.1
        imagePullPolicy: IfNotPresent
        name: alertmanager-bot
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: alertmanager-bot
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: alertmanager-bot
        persistentVolumeClaim:
          claimName: alertmanager-bot-vol
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-11-08T16:43:24Z"
    lastUpdateTime: "2020-06-03T14:58:39Z"
    message: ReplicaSet "alertmanager-bot-5fd578b9d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-28T06:06:43Z"
    lastUpdateTime: "2022-05-28T06:06:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
