apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"alertmanager","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"alertmanager"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"alertmanagerHash":"9f7be47249ef3ab762bb595e3fb0fe5c55e4e4540e62274835940686de31e925","alertmanagerTemplatesHash":"c0700e417446f0d49048ba60d0b59e9e0fa02b6700259f4b61ee8e95ae2dc22f"},"labels":{"app":"alertmanager"},"name":"alertmanager"},"spec":{"containers":[{"args":["--config.file=/etc/alertmanager/config.yml","--storage.path=/alertmanager","--web.external-url=$(EXTERNAL_URL)/alertmanager"],"env":[{"name":"EXTERNAL_URL","value":"http://alertmanager.stage.bookful.inceptionxr.com/"}],"image":"prom/alertmanager:latest","name":"alertmanager","ports":[{"containerPort":9093,"name":"alertmanager"}],"resources":{"limits":{"cpu":"0.1","memory":"50Mi"},"requests":{"cpu":"0.01","memory":"20Mi"}},"volumeMounts":[{"mountPath":"/etc/alertmanager","name":"config-volume"},{"mountPath":"/etc/alertmanager-templates","name":"templates-volume"},{"mountPath":"/alertmanager","name":"alertmanager"}]}],"volumes":[{"configMap":{"name":"alertmanager"},"name":"config-volume"},{"configMap":{"name":"alertmanager-templates"},"name":"templates-volume"},{"name":"alertmanager","persistentVolumeClaim":{"claimName":"alertmanager-vol"}}]}}}}
  creationTimestamp: "2018-11-07T17:07:39Z"
  generation: 7
  name: alertmanager
  namespace: monitoring
  resourceVersion: "738597024"
  uid: a1762de4-e2af-11e8-873c-42010a800271
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        alertmanagerHash: 9f7be47249ef3ab762bb595e3fb0fe5c55e4e4540e62274835940686de31e925
        alertmanagerTemplatesHash: c0700e417446f0d49048ba60d0b59e9e0fa02b6700259f4b61ee8e95ae2dc22f
      creationTimestamp: null
      labels:
        app: alertmanager
      name: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        - --web.external-url=$(EXTERNAL_URL)/alertmanager
        env:
        - name: EXTERNAL_URL
          value: http://alertmanager.stage.bookful.inceptionxr.com/
        image: prom/alertmanager:latest
        imagePullPolicy: Always
        name: alertmanager
        ports:
        - containerPort: 9093
          name: alertmanager
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: config-volume
        - mountPath: /etc/alertmanager-templates
          name: templates-volume
        - mountPath: /alertmanager
          name: alertmanager
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: alertmanager
        name: config-volume
      - configMap:
          defaultMode: 420
          name: alertmanager-templates
        name: templates-volume
      - name: alertmanager
        persistentVolumeClaim:
          claimName: alertmanager-vol
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-11-07T17:07:39Z"
    lastUpdateTime: "2019-08-12T07:51:45Z"
    message: ReplicaSet "alertmanager-5884ccc9bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-28T06:06:46Z"
    lastUpdateTime: "2022-05-28T06:06:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
