apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"grafana"},"name":"grafana","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"grafana"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"dashboardsSet1Hash":"ad9be3b92ab5181adadd92cb9215747ed6804510f5b082316013d897baaf2f6a","dashboardsSet2Hash":"99c7b289fc663dc74df1c14397f936842aff77f3f3daf32290cef0e54cd6710e","dataSourcesHash":"5fdfd271f1f7c97fbd0f355409838de62ee150f5b3a271e5ea4f00045b2e75cb","provisioningDashboardsHash":"9697a2a4dab6422c9bf4a22cdc35549c905c8c5e026946aecaa7a5b5bdaf69c2"},"labels":{"name":"grafana"}},"spec":{"containers":[{"env":[{"name":"GF_SECURITY_ADMIN_USER","value":"admin"},{"name":"GF_SECURITY_ADMIN_PASSWORD","value":"maZ8wTHY6rVYZZPDxKW4TByF35v8M4DzUtkmQnMhgK2SszTMnZFaXHEUX44npunhafpHDpZAP3rdGN8Ga4AcrhwEz9TTDKAtPNp9mKnXVBMBWf8C5WCMaFkWxr58Tbwb"},{"name":"GF_USERS_ALLOW_SIGN_UP","value":"false"},{"name":"GF_SERVER_ROOT_URL","value":"http://grafana.stage.bookful.inceptionxr.com"}],"image":"grafana/grafana:7.2.0","imagePullPolicy":"IfNotPresent","name":"grafana","ports":[{"containerPort":3000,"protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/login","port":3000}},"resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"10m","memory":"100Mi"}},"securityContext":{"runAsUser":0},"volumeMounts":[{"mountPath":"/var/lib/grafana","name":"data-grafana"},{"mountPath":"/var/lib/grafana/dashboards/set-1","name":"grafana-dashboards-set-1"},{"mountPath":"/var/lib/grafana/dashboards/set-2","name":"grafana-dashboards-set-2"},{"mountPath":"/etc/grafana/provisioning/dashboards","name":"grafana-provisioning-dashboards"},{"mountPath":"/etc/grafana/provisioning/datasources","name":"grafana-provisioning-datasources"}]}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"name":"grafana-dashboards-config-set-1"},"name":"grafana-dashboards-set-1"},{"configMap":{"name":"grafana-dashboards-config-set-2"},"name":"grafana-dashboards-set-2"},{"configMap":{"name":"grafana-provisioning-dashboards-config"},"name":"grafana-provisioning-dashboards"},{"configMap":{"name":"grafana-provisioning-datasources-config"},"name":"grafana-provisioning-datasources"},{"name":"data-grafana","persistentVolumeClaim":{"claimName":"grafana-vol"}}]}}}}
  creationTimestamp: "2018-11-06T15:08:03Z"
  generation: 13
  labels:
    name: grafana
  name: grafana
  namespace: monitoring
  resourceVersion: "738597064"
  uid: c221158d-e1d5-11e8-873c-42010a800271
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        dashboardsSet1Hash: ad9be3b92ab5181adadd92cb9215747ed6804510f5b082316013d897baaf2f6a
        dashboardsSet2Hash: 99c7b289fc663dc74df1c14397f936842aff77f3f3daf32290cef0e54cd6710e
        dataSourcesHash: 5fdfd271f1f7c97fbd0f355409838de62ee150f5b3a271e5ea4f00045b2e75cb
        provisioningDashboardsHash: 9697a2a4dab6422c9bf4a22cdc35549c905c8c5e026946aecaa7a5b5bdaf69c2
      creationTimestamp: null
      labels:
        name: grafana
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: maZ8wTHY6rVYZZPDxKW4TByF35v8M4DzUtkmQnMhgK2SszTMnZFaXHEUX44npunhafpHDpZAP3rdGN8Ga4AcrhwEz9TTDKAtPNp9mKnXVBMBWf8C5WCMaFkWxr58Tbwb
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_SERVER_ROOT_URL
          value: http://grafana.stage.bookful.inceptionxr.com
        image: grafana/grafana:7.2.0
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: data-grafana
        - mountPath: /var/lib/grafana/dashboards/set-1
          name: grafana-dashboards-set-1
        - mountPath: /var/lib/grafana/dashboards/set-2
          name: grafana-dashboards-set-2
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-provisioning-dashboards
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-provisioning-datasources
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: grafana-dashboards-config-set-1
        name: grafana-dashboards-set-1
      - configMap:
          defaultMode: 420
          name: grafana-dashboards-config-set-2
        name: grafana-dashboards-set-2
      - configMap:
          defaultMode: 420
          name: grafana-provisioning-dashboards-config
        name: grafana-provisioning-dashboards
      - configMap:
          defaultMode: 420
          name: grafana-provisioning-datasources-config
        name: grafana-provisioning-datasources
      - name: data-grafana
        persistentVolumeClaim:
          claimName: grafana-vol
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-11-06T15:08:03Z"
    lastUpdateTime: "2020-09-29T15:28:02Z"
    message: ReplicaSet "grafana-6bd7b5c544" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-28T06:06:51Z"
    lastUpdateTime: "2022-05-28T06:06:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
